### ISSUE TITLE
Feature Request: Add ability to collapse subtests

### ISSUE THREAD

**Issue by StevenACoffman** [haveyoudebuggedit/gotestfmt#58]
Currently, when you have subtests, they are treated as entirely separate tests by gotestfmt. This makes the parent test empty when you expand it.
I would like an empty parent of subtests to provide a collapse/summary for it's subtests instead.

<img width="559" alt="Screenshot 2024-06-18 at 9 30 59 PM" src="https://github.com/GoTestTools/gotestfmt/assets/1942608/594763ce-5b3b-4f6b-94a1-3151efecd16b">

An example subtest:
```
func TestTime(t *testing.T) {
    testCases := []struct {
        gmt  string
        loc  string
        want string
    }{
        {"12:31", "Europe/Zuri", "13:31"},
        {"12:31", "America/New_York", "7:31"},
        {"08:08", "Australia/Sydney", "18:08"},
    }
    for _, tc := range testCases {
        t.Run(fmt.Sprintf("%s in %s", tc.gmt, tc.loc), func(t *testing.T) {
            loc, err := time.LoadLocation(tc.loc)
            if err != nil {
                t.Fatal("could not load location")
            }
            gmt, _ := time.Parse("15:04", tc.gmt)
            if got := gmt.In(loc).Format("15:04"); got != tc.want {
                t.Errorf("got %s; want %s", got, tc.want)
            }
        })
    }
}
```

**Comment by ghost** [comment]
Hi @StevenACoffman thank you for your request. This, unfortunately, runs contrary to how gotestfmt is built since the parent test can also produce output that should be recorded. As a default behavior, gotestfmt shouldn't output anything if the test itself didn't write anything because it can get confusing where the data came from.

Furthermore, the current architecture of gotestfmt doesn't keep tests buffered, they are sent to the renderer as they come in the output, so we can't implement this feature without significant rearchitecting and an increase in memory consumption. Since [a lot of people rely on gotestfmt](https://github.com/search?q=gotestfmt&type=code) to do exactly what it does, I'm personally disinclined to change the codebase significantly.

@StevenACoffman would you be willing to work on the implementation of this feature? @engelmi @jaredoconnell do you have capacity to work on this or review a community PR in-depth if @StevenACoffman or someone else were to implement this feature? I currently do not have capacity to work on this.

**Comment by StevenACoffman** [comment]
I would defer closing **_any_** item until the next one and keep a count of how many unclosed remained so they could nest arbitrarily deep, and then have a cleanup that closed all the remaining items, if any. This new behavior could be gated by a configuration flag.

> This, unfortunately, runs contrary to how gotestfmt is built since the parent test can also produce output that should be recorded. As a default behavior, gotestfmt shouldn't output anything if the test itself didn't write anything because it can get confusing where the data came from.
> 
> Furthermore, the current architecture of gotestfmt doesn't keep tests buffered, they are sent to the renderer as they come in the output, so we can't implement this feature without significant rearchitecting and an increase in memory consumption. Since [a lot of people rely on gotestfmt](https://github.com/search?q=gotestfmt&type=code) to do exactly what it does, I'm personally disinclined to change the codebase significantly.

That's entirely fair! So it might not be accepted even if I implemented it because it might add to the complexity and resource consumption. No worries! Thanks for making, sharing, and maintaining a useful thing!
